-- Initialization scripts for local databases

CREATE USER in940 IDENTIFIED BY pass;

GRANT CONNECT, RESOURCE, DBA to in940;

CREATE OR REPLACE TRIGGER on_user_logon
    AFTER LOGON ON DATABASE
    WHEN (USER = 'in940')
BEGIN
    EXECUTE IMMEDIATE 'ALTER SESSION SET CURRENT_SCHEMA = in940';
END;
