ALTER TYPE TP_REL_INCLUI ADD MEMBER FUNCTION valorTotal RETURN NUMBER CASCADE;

CREATE OR REPLACE TYPE BODY TP_REL_INCLUI AS
    MEMBER FUNCTION valorTotal RETURN NUMBER IS
        BEGIN
            RETURN QUANTIDADE * VALOR;
        END;
END;
/
